version: 1
formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: outputs/logs/pipeline.log
loggers:
  "":
    level: INFO
    handlers: [console, file]
    propagate: false
